#!/bin/bash

if [[ -n $2 ]]; then
    if [[ $1 == "f" ]]; then
        tests=$2
    else
        tests=$(find Testframework/project2/$1 -name "*${2}*.rc" | sort -n)
    fi
else
    tests=$(find Testframework/project2/* -mindepth 1 -name "*${1}*.rc" | sort -n)
fi
for f in $tests; do
    echo "\n================================================================================\n"
    echo "Compiling $f..."
    ./RC $f
    echo "Compiling assembly..."
    make compile
    echo "Running a.out..."
    echo "\nOutput:"
    echo "----------------------------------------\n"
    ./a.out
    echo "\n----------------------------------------"
done
